import { expect, test } from '@playwright/test'

test('records, persists, analyzes, and exports a complete multi-peak session', async ({ page }) => {
  const consoleErrors: string[] = []; const failedRequests: string[] = []
  page.on('console', message => { if (message.type() === 'error') consoleErrors.push(message.text()) })
  page.on('requestfailed', request => failedRequests.push(`${request.method()} ${request.url()} ${request.failure()?.errorText}`))
  await page.addInitScript(() => localStorage.setItem('ht-test-time', '2026-07-20T18:00:00.000Z'))
  await page.goto('/')

  await page.getByRole('button', { name: 'Skip intro' }).click()
  await page.getByRole('checkbox').check()
  await page.getByRole('button', { name: /Enter journal/ }).click()
  await expect(page.getByRole('heading', { name: /Notice the whole arc/ })).toBeVisible()
  await page.screenshot({ path: 'artifacts/screenshots/home-dashboard.png', fullPage: true })

  await page.getByRole('link', { name: /Start session/ }).click()
  await page.getByLabel(/Product or strain/).fill('Night Orchard')
  await page.getByRole('button', { name: /Start timeline/ }).click()
  await page.getByRole('button', { name: 'Feeling it', exact: true }).click()
  await page.getByRole('button', { name: 'High', exact: true }).click()
  await page.getByRole('button', { name: 'Super high', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'Super high' })).toBeVisible()
  await page.screenshot({ path: 'artifacts/screenshots/active-super-high.png', fullPage: true })

  await page.getByRole('button', { name: /Add event/ }).click()
  await expect(page.getByRole('dialog', { name: 'Add to this timeline' })).toBeVisible()
  await page.screenshot({ path: 'artifacts/screenshots/add-event-sheet.png', fullPage: true })
  await page.getByRole('button', { name: /Cigarette \/ nicotine/ }).click()
  await page.getByRole('button', { name: 'Coming down', exact: true }).click()
  await page.getByRole('button', { name: /Add event/ }).click()
  await page.getByRole('button', { name: /More of the same/ }).click()
  await page.getByRole('button', { name: 'Super high', exact: true }).click()
  await page.getByRole('button', { name: 'Effects' }).click()
  await page.getByRole('button', { name: /Dreamy/ }).click()
  await page.getByRole('button', { name: /Hungry/ }).click()
  await page.getByRole('button', { name: /Calm/ }).click()
  await page.getByRole('button', { name: /Save 3 effects/ }).click()
  await page.getByRole('button', { name: 'Coming down', exact: true }).click()
  await page.getByRole('button', { name: 'Back to normal', exact: true }).click()
  await expect(page.getByRole('dialog', { name: 'End this session?' })).toBeVisible()
  await page.getByRole('button', { name: 'End now' }).click()
  await page.getByRole('button', { name: 'Rate 9 out of 10' }).click()
  await page.getByRole('button', { name: 'Yes' }).click()
  await page.getByRole('button', { name: 'Save recap' }).click()

  await expect(page.getByRole('heading', { name: 'Night Orchard' })).toBeVisible()
  const peaks = page.locator('.metrics-grid article').filter({ hasText: 'Separate peaks' })
  await expect(peaks).toContainText('2')
  const superHigh = page.locator('.metrics-grid article').filter({ hasText: 'Super high total' })
  await expect(superHigh.locator('strong')).not.toHaveText('0 min')
  await page.screenshot({ path: 'artifacts/screenshots/completed-multi-peak-summary.png', fullPage: true })

  await page.reload()
  await expect(page.getByRole('heading', { name: 'Night Orchard' })).toBeVisible()
  await page.getByRole('navigation', { name: 'Primary' }).getByRole('link', { name: 'History' }).click()
  await expect(page.getByText('Night Orchard').first()).toBeVisible()
  await page.screenshot({ path: 'artifacts/screenshots/history.png', fullPage: true })
  await page.getByRole('navigation', { name: 'Primary' }).getByRole('link', { name: 'Insights' }).click()
  await expect(page.getByRole('heading', { name: 'Night Orchard' })).toBeVisible()
  await page.screenshot({ path: 'artifacts/screenshots/insights.png', fullPage: true })
  await page.getByRole('navigation', { name: 'Primary' }).getByRole('link', { name: 'Settings' }).click()
  const download = page.waitForEvent('download')
  await page.getByRole('button', { name: /Export JSON backup/ }).click()
  expect((await download).suggestedFilename()).toMatch(/^high-timeline-.*\.json$/)

  expect(consoleErrors).toEqual([])
  expect(failedRequests).toEqual([])
})
