import { expect, test } from '@playwright/test'

test('records, persists, analyzes, and exports a complete multi-peak session', async ({ page }) => {
  const consoleErrors: string[] = []; const failedRequests: string[] = []
  page.on('console', message => { if (message.type() === 'error') consoleErrors.push(message.text()) })
  page.on('requestfailed', request => failedRequests.push(`${request.method()} ${request.url()} ${request.failure()?.errorText}`))
  await page.addInitScript(() => localStorage.setItem('ht-test-time', '2026-07-20T18:00:00.000Z'))
  await page.goto('/')

  await page.getByRole('button', { name: 'Skip intro' }).click()
  await page.getByRole('checkbox').check()
  await page.getByRole('button', { name: /Enter journal/ }).click()
  await expect(page.getByRole('heading', { name: /How are you feeling/ })).toBeVisible()
  await page.screenshot({ path: 'artifacts/screenshots/home-dashboard.png', fullPage: true })

  await page.getByRole('link', { name: /Start session/ }).click()
  await page.getByLabel(/Product or strain/).fill('Night Orchard')
  await page.getByRole('button', { name: /Start timeline/ }).click()
  await page.getByRole('button', { name: 'Feeling it', exact: true }).click()
  await page.getByRole('button', { name: 'High', exact: true }).click()
  await page.getByRole('button', { name: 'Super high', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'Super high' })).toBeVisible()
  await page.screenshot({ path: 'artifacts/screenshots/active-super-high.png', fullPage: true })

  await page.getByRole('button', { name: 'Comfort' }).click()
  const comfort = page.getByRole('dialog', { name: 'Comfort mode' })
  await expect(comfort.getByText(/does not measure intoxication/i)).toBeVisible()
  await comfort.getByRole('button', { name: 'Start breathing' }).click()
  await expect(comfort.getByText('Breathe in gently')).toBeVisible()
  await page.screenshot({ path: 'artifacts/screenshots/comfort-breathing.png', fullPage: true })
  await page.emulateMedia({ reducedMotion: 'reduce' })
  await expect(comfort.locator('.breath-halo')).toHaveCSS('animation-name', 'none')
  await page.emulateMedia({ reducedMotion: 'no-preference' })
  await comfort.getByRole('button', { name: 'Close' }).click()

  await page.getByRole('button', { name: /Add event/ }).click()
  await expect(page.getByRole('dialog', { name: 'Add to this timeline' })).toBeVisible()
  await page.screenshot({ path: 'artifacts/screenshots/add-event-sheet.png', fullPage: true })
  await page.getByRole('button', { name: /Cigarette \/ nicotine/ }).click()
  await page.getByRole('button', { name: 'Coming down', exact: true }).click()
  await page.getByRole('button', { name: /Add event/ }).click()
  await page.getByRole('button', { name: /More of the same/ }).click()
  await page.getByRole('button', { name: 'Super high', exact: true }).click()
  await page.getByRole('button', { name: 'Effects' }).click()
  await page.getByRole('button', { name: /Happy/ }).click()
  await page.getByRole('button', { name: /Dreamy/ }).click()
  await page.getByRole('button', { name: /Calm/ }).click()
  await page.getByRole('button', { name: /Save 3 effects/ }).click()
  await page.getByRole('button', { name: 'High', exact: true }).click()
  await expect(page.getByTestId('zanana-mascot')).toHaveAttribute('data-pose', 'high-happy')
  await expect(page.getByText('Happy').first()).toBeVisible()
  await page.screenshot({ path: 'artifacts/screenshots/active-high-happy.png', fullPage: true })
  await page.getByRole('navigation', { name: 'Primary' }).getByRole('link', { name: 'Home' }).click()
  await expect(page.getByText('Your live timeline')).toBeVisible()
  await expect(page.getByRole('heading', { name: 'High' })).toBeVisible()
  await expect(page.getByRole('navigation', { name: 'Primary' }).getByRole('link', { name: 'Timeline' })).toBeVisible()
  await page.screenshot({ path: 'artifacts/screenshots/home-active-timeline.png', fullPage: true })
  await page.getByRole('navigation', { name: 'Primary' }).getByRole('link', { name: 'Timeline' }).click()
  await page.getByRole('button', { name: /End session/ }).click()
  await expect(page.getByRole('dialog', { name: 'End this session?' })).toBeVisible()
  await page.getByRole('button', { name: 'Close', exact: true }).click()
  await page.emulateMedia({ reducedMotion: 'reduce' })
  await expect(page.getByTestId('zanana-mascot').locator('img')).toHaveCSS('animation-name', 'none')
  await expect(page.getByTestId('zanana-mascot').locator('img')).toHaveAttribute('alt', '')
  await page.getByRole('button', { name: 'Coming down', exact: true }).click()
  await page.getByRole('button', { name: 'Back to normal', exact: true }).click()
  await expect(page.getByRole('dialog', { name: 'End this session?' })).toBeVisible()
  await page.getByRole('button', { name: 'End now' }).click()
  await expect(page.getByRole('heading', { name: /How are you feeling/ })).toBeVisible()
  await page.getByText('Night Orchard').first().click()
  await expect(page.getByRole('heading', { name: 'Night Orchard' })).toBeVisible()
  const peaks = page.locator('.metrics-grid article').filter({ hasText: 'Separate peaks' })
  await expect(peaks).toContainText('2')
  const superHigh = page.locator('.metrics-grid article').filter({ hasText: 'Super high total' })
  await expect(superHigh.locator('strong')).not.toHaveText('0 min')
  await page.screenshot({ path: 'artifacts/screenshots/completed-multi-peak-summary.png', fullPage: true })

  await page.getByRole('button', { name: 'Bookmark Cigarette/nicotine' }).click()
  const bookmark = page.getByRole('dialog', { name: 'Save this moment' })
  await bookmark.getByLabel(/Label/).fill('The music felt especially clear')
  await bookmark.getByLabel('Choose bookmark photo').setInputFiles({name:'orchard.svg',mimeType:'image/svg+xml',buffer:Buffer.from('<svg xmlns="http://www.w3.org/2000/svg" width="120" height="80"><rect width="120" height="80" fill="#f4d66d"/><circle cx="60" cy="40" r="24" fill="#62ad69"/></svg>')})
  await expect(bookmark.getByAltText('Bookmark attachment preview')).toBeVisible()
  await page.screenshot({ path: 'artifacts/screenshots/bookmark-keepsake.png', fullPage: true })
  await bookmark.getByRole('button', { name:'Save bookmark' }).click()
  await expect(page.getByRole('button', { name:'Edit bookmark for Cigarette/nicotine' })).toHaveAttribute('aria-pressed','true')

  await page.reload()
  await expect(page.getByRole('heading', { name: 'Night Orchard' })).toBeVisible()
  await page.getByRole('button', { name:'Edit bookmark for Cigarette/nicotine' }).click()
  await expect(page.getByRole('dialog', { name:'Edit bookmark' }).getByAltText('Bookmark attachment preview')).toBeVisible()
  await page.getByRole('dialog', { name:'Edit bookmark' }).getByRole('button', { name:'Close' }).click()
  await page.getByRole('link', { name: 'Edit timeline' }).click()
  await page.getByRole('button', { name: 'Add missed event' }).click()
  const missedDialog = page.getByRole('dialog', { name: 'Add missed event' })
  await missedDialog.getByLabel('Type').selectOption('CONSUME')
  await missedDialog.getByLabel('Name or category').fill('1 cig')
  const addMissedButton = missedDialog.getByRole('button', { name: 'Add event' })
  await expect(addMissedButton).toBeInViewport()
  await addMissedButton.click()
  await expect(missedDialog).toBeHidden()
  await expect(page.getByText('1 cig')).toBeVisible()
  await page.getByRole('button', { name: 'Back to session' }).click()
  await page.getByRole('navigation', { name: 'Primary' }).getByRole('link', { name: 'History' }).click()
  await expect(page.getByText('Night Orchard').first()).toBeVisible()
  await expect(page.getByText('1 bookmark across your journal')).toBeVisible()
  await page.getByRole('button', { name:'Show bookmarks only' }).click()
  await expect(page.getByText('Night Orchard').first()).toBeVisible()
  await page.screenshot({ path: 'artifacts/screenshots/history.png', fullPage: true })
  await page.getByRole('navigation', { name: 'Primary' }).getByRole('link', { name: 'Insights' }).click()
  await expect(page.getByRole('heading', { name: 'Night Orchard' })).toBeVisible()
  await page.screenshot({ path: 'artifacts/screenshots/insights.png', fullPage: true })
  await page.getByRole('navigation', { name: 'Primary' }).getByRole('link', { name: 'Game' }).click()
  await expect(page.getByRole('heading', { name: 'Zanana Pop!' })).toBeVisible()
  await page.getByRole('button', { name: 'Start round' }).click()
  await page.getByRole('button', { name: 'Bop Zanana' }).click()
  await expect(page.locator('.game-scoreboard strong').first()).toHaveText('1')
  await page.screenshot({ path: 'artifacts/screenshots/zanana-pop.png', fullPage: true })
  for (let bop = 1; bop < 8; bop += 1) await page.getByRole('button', { name: 'Bop Zanana' }).click()
  await page.getByRole('navigation', { name: 'Zanana play spaces' }).getByRole('link', { name: /Zanana’s Room/ }).click()
  await expect(page.getByRole('heading', { name: 'Zanana’s Room' })).toBeVisible()
  await expect(page.getByLabel('8 sunshine available')).toBeVisible()
  await page.getByRole('button', { name: /Garden crown/ }).click()
  await expect(page.getByRole('button', { name: /Garden crown/ })).toHaveAttribute('aria-pressed', 'true')
  await page.screenshot({ path: 'artifacts/screenshots/zananas-room.png', fullPage: true })
  await page.getByRole('link', { name: 'Settings' }).click()
  const download = page.waitForEvent('download')
  await page.getByRole('button', { name: /Export JSON backup/ }).click()
  expect((await download).suggestedFilename()).toMatch(/^zanana-.*\.json$/)

  expect(consoleErrors).toEqual([])
  expect(failedRequests).toEqual([])
})
